# Generated by Django 3.1 on 2020-08-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usedCalories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('meal', models.TextField()),
                ('calories', models.IntegerField()),
            ],
        ),
    ]
