# Generated by Django 3.1 on 2020-08-31 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kalorienzaehler', '0002_auto_20200831_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedcalories',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
