# Generated by Django 3.1 on 2020-08-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalorienzaehler', '0006_usedcalories_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedcalories',
            name='meal',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usedcalories',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
