# Generated by Django 3.1 on 2020-09-01 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalorienzaehler', '0008_auto_20200901_1209'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Nutzer',
        ),
    ]
