# Generated by Django 3.1 on 2020-09-01 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kalorienzaehler', '0009_auto_20200901_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedcalories',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kalorienzaehler.nutzer'),
        ),
    ]
