# Generated by Django 3.1 on 2020-09-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalorienzaehler', '0010_usedcalories_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutzer',
            name='loseWeight',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='nutzer',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
