# Generated by Django 3.1 on 2020-09-01 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalorienzaehler', '0011_auto_20200901_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutzer',
            old_name='loseWeight',
            new_name='maxCalories',
        ),
        migrations.RemoveField(
            model_name='nutzer',
            name='weight',
        ),
    ]
