# Generated by Django 3.1 on 2020-09-01 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalorienzaehler', '0012_auto_20200901_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usedcalories',
            old_name='calories',
            new_name='Kilokalorien',
        ),
        migrations.RenameField(
            model_name='usedcalories',
            old_name='meal',
            new_name='Mahlzeit',
        ),
    ]
